// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuGPcS7O9ajbPlc6Ln3-i7-kBVTKRKTbA',
    appId: '1:96015837752:web:435ba86ac1e262994814cd',
    messagingSenderId: '96015837752',
    projectId: 'pressing-opropre',
    authDomain: 'pressing-opropre.firebaseapp.com',
    storageBucket: 'pressing-opropre.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAA78parQJpWDZKlam50AdlPWfdnLMfns',
    appId: '1:96015837752:android:790299461c2f50434814cd',
    messagingSenderId: '96015837752',
    projectId: 'pressing-opropre',
    storageBucket: 'pressing-opropre.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb5LhLr67WfVWpnGiET0KnBm2BWkKPyqo',
    appId: '1:96015837752:ios:e9fa84faf0c6a6b84814cd',
    messagingSenderId: '96015837752',
    projectId: 'pressing-opropre',
    storageBucket: 'pressing-opropre.firebasestorage.app',
    iosBundleId: 'com.example.pressingOpropre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb5LhLr67WfVWpnGiET0KnBm2BWkKPyqo',
    appId: '1:96015837752:ios:e9fa84faf0c6a6b84814cd',
    messagingSenderId: '96015837752',
    projectId: 'pressing-opropre',
    storageBucket: 'pressing-opropre.firebasestorage.app',
    iosBundleId: 'com.example.pressingOpropre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuGPcS7O9ajbPlc6Ln3-i7-kBVTKRKTbA',
    appId: '1:96015837752:web:99abe50e7e88e98b4814cd',
    messagingSenderId: '96015837752',
    projectId: 'pressing-opropre',
    authDomain: 'pressing-opropre.firebaseapp.com',
    storageBucket: 'pressing-opropre.firebasestorage.app',
  );
}
